mv ./autoconf/ansi2knr.cpp ./autoconf/ansi2knr.c
mv ./win32/d2dbs_winmain.cpp ./win32/d2dbs_winmain.c
mv ./win32/winmain.cpp ./win32/winmain.c
mv ./win32/service.cpp ./win32/service.c
mv ./win32/d2cs_winmain.cpp ./win32/d2cs_winmain.c
mv ./bnproxy/bnproxy.cpp ./bnproxy/bnproxy.c
mv ./bnproxy/virtconn.cpp ./bnproxy/virtconn.c
mv ./tinycdb/cdb_find.cpp ./tinycdb/cdb_find.c
mv ./tinycdb/cdb_make.cpp ./tinycdb/cdb_make.c
mv ./tinycdb/cdb_seek.cpp ./tinycdb/cdb_seek.c
mv ./tinycdb/cdb.cpp ./tinycdb/cdb.c
mv ./tinycdb/cdb_make_add.cpp ./tinycdb/cdb_make_add.c
mv ./tinycdb/cdb_make_put.cpp ./tinycdb/cdb_make_put.c
mv ./tinycdb/cdb_seq.cpp ./tinycdb/cdb_seq.c
mv ./tinycdb/cdb_make_find.cpp ./tinycdb/cdb_make_find.c
mv ./tinycdb/cdb_hash.cpp ./tinycdb/cdb_hash.c
mv ./tinycdb/cdb_init.cpp ./tinycdb/cdb_init.c
mv ./tinycdb/cdb_unpack.cpp ./tinycdb/cdb_unpack.c
mv ./tinycdb/cdb_findnext.cpp ./tinycdb/cdb_findnext.c
mv ./client/bnftp.cpp ./client/bnftp.c
mv ./client/client.cpp ./client/client.c
mv ./client/bnbot.cpp ./client/bnbot.c
mv ./client/bnstat.cpp ./client/bnstat.c
mv ./client/udptest.cpp ./client/udptest.c
mv ./client/bnchat.cpp ./client/bnchat.c
mv ./client/client_connect.cpp ./client/client_connect.c
mv ./bnetd/handle_udp.cpp ./bnetd/handle_udp.c
mv ./bnetd/alias_command.cpp ./bnetd/alias_command.c
mv ./bnetd/helpfile.cpp ./bnetd/helpfile.c
mv ./bnetd/server.cpp ./bnetd/server.c
mv ./bnetd/storage_sql.cpp ./bnetd/storage_sql.c
mv ./bnetd/game_conv.cpp ./bnetd/game_conv.c
mv ./bnetd/connection.cpp ./bnetd/connection.c
mv ./bnetd/file_plain.cpp ./bnetd/file_plain.c
mv ./bnetd/account.cpp ./bnetd/account.c
mv ./bnetd/ipban.cpp ./bnetd/ipban.c
mv ./bnetd/adbanner.cpp ./bnetd/adbanner.c
mv ./bnetd/ladder.cpp ./bnetd/ladder.c
mv ./bnetd/tick.cpp ./bnetd/tick.c
mv ./bnetd/attrlayer.cpp ./bnetd/attrlayer.c
mv ./bnetd/message.cpp ./bnetd/message.c
mv ./bnetd/storage_file.cpp ./bnetd/storage_file.c
mv ./bnetd/ladder_binary.cpp ./bnetd/ladder_binary.c
mv ./bnetd/anongame_gameresult.cpp ./bnetd/anongame_gameresult.c
mv ./bnetd/character.cpp ./bnetd/character.c
mv ./bnetd/cmdline.cpp ./bnetd/cmdline.c
mv ./bnetd/game.cpp ./bnetd/game.c
mv ./bnetd/support.cpp ./bnetd/support.c
mv ./bnetd/command_groups.cpp ./bnetd/command_groups.c
mv ./bnetd/topic.cpp ./bnetd/topic.c
mv ./bnetd/sql_dbcreator.cpp ./bnetd/sql_dbcreator.c
mv ./bnetd/attrgroup.cpp ./bnetd/attrgroup.c
mv ./bnetd/sql_mysql.cpp ./bnetd/sql_mysql.c
mv ./bnetd/handle_file.cpp ./bnetd/handle_file.c
mv ./bnetd/handle_anongame.cpp ./bnetd/handle_anongame.c
mv ./bnetd/timer.cpp ./bnetd/timer.c
mv ./bnetd/channel.cpp ./bnetd/channel.c
mv ./bnetd/anongame.cpp ./bnetd/anongame.c
mv ./bnetd/tournament.cpp ./bnetd/tournament.c
mv ./bnetd/mail.cpp ./bnetd/mail.c
mv ./bnetd/udptest_send.cpp ./bnetd/udptest_send.c
mv ./bnetd/prefs.cpp ./bnetd/prefs.c
mv ./bnetd/main.cpp ./bnetd/main.c
mv ./bnetd/output.cpp ./bnetd/output.c
mv ./bnetd/channel_conv.cpp ./bnetd/channel_conv.c
mv ./bnetd/sql_pgsql.cpp ./bnetd/sql_pgsql.c
mv ./bnetd/friends.cpp ./bnetd/friends.c
mv ./bnetd/ladder_calc.cpp ./bnetd/ladder_calc.c
mv ./bnetd/handle_bot.cpp ./bnetd/handle_bot.c
mv ./bnetd/handle_bnet.cpp ./bnetd/handle_bnet.c
mv ./bnetd/versioncheck.cpp ./bnetd/versioncheck.c
mv ./bnetd/clan.cpp ./bnetd/clan.c
mv ./bnetd/sql_odbc.cpp ./bnetd/sql_odbc.c
mv ./bnetd/command.cpp ./bnetd/command.c
mv ./bnetd/handle_irc.cpp ./bnetd/handle_irc.c
mv ./bnetd/handle_d2cs.cpp ./bnetd/handle_d2cs.c
mv ./bnetd/news.cpp ./bnetd/news.c
mv ./bnetd/file_cdb.cpp ./bnetd/file_cdb.c
mv ./bnetd/anongame_infos.cpp ./bnetd/anongame_infos.c
mv ./bnetd/team.cpp ./bnetd/team.c
mv ./bnetd/file.cpp ./bnetd/file.c
mv ./bnetd/anongame_maplists.cpp ./bnetd/anongame_maplists.c
mv ./bnetd/runprog.cpp ./bnetd/runprog.c
mv ./bnetd/tracker.cpp ./bnetd/tracker.c
mv ./bnetd/autoupdate.cpp ./bnetd/autoupdate.c
mv ./bnetd/irc.cpp ./bnetd/irc.c
mv ./bnetd/handle_init.cpp ./bnetd/handle_init.c
mv ./bnetd/sql_sqlite3.cpp ./bnetd/sql_sqlite3.c
mv ./bnetd/storage.cpp ./bnetd/storage.c
mv ./bnetd/handle_telnet.cpp ./bnetd/handle_telnet.c
mv ./bnetd/realm.cpp ./bnetd/realm.c
mv ./bnetd/account_wrap.cpp ./bnetd/account_wrap.c
mv ./bnetd/watch.cpp ./bnetd/watch.c
mv ./d2dbs/dbserver.cpp ./d2dbs/dbserver.c
mv ./d2dbs/dbsdupecheck.cpp ./d2dbs/dbsdupecheck.c
mv ./d2dbs/handle_signal.cpp ./d2dbs/handle_signal.c
mv ./d2dbs/cmdline_parse.cpp ./d2dbs/cmdline_parse.c
mv ./d2dbs/d2ladder.cpp ./d2dbs/d2ladder.c
mv ./d2dbs/dbspacket.cpp ./d2dbs/dbspacket.c
mv ./d2dbs/charlock.cpp ./d2dbs/charlock.c
mv ./d2dbs/prefs.cpp ./d2dbs/prefs.c
mv ./d2dbs/main.cpp ./d2dbs/main.c
mv ./zlib/pvpgn_zutil.cpp ./zlib/pvpgn_zutil.c
mv ./zlib/pvpgn_deflate.cpp ./zlib/pvpgn_deflate.c
mv ./zlib/pvpgn_adler32.cpp ./zlib/pvpgn_adler32.c
mv ./zlib/pvpgn_trees.cpp ./zlib/pvpgn_trees.c
mv ./bniutils/bnilist.cpp ./bniutils/bnilist.c
mv ./bniutils/tgainfo.cpp ./bniutils/tgainfo.c
mv ./bniutils/fileio.cpp ./bniutils/fileio.c
mv ./bniutils/tga.cpp ./bniutils/tga.c
mv ./bniutils/bnibuild.cpp ./bniutils/bnibuild.c
mv ./bniutils/bni.cpp ./bniutils/bni.c
mv ./bniutils/bniextract.cpp ./bniutils/bniextract.c
mv ./bniutils/bni2tga.cpp ./bniutils/bni2tga.c
mv ./common/fdwatch_poll.cpp ./common/fdwatch_poll.c
mv ./common/list.cpp ./common/list.c
mv ./common/fdwatch.cpp ./common/fdwatch.c
mv ./common/give_up_root_privileges.cpp ./common/give_up_root_privileges.c
mv ./common/tag.cpp ./common/tag.c
mv ./common/queue.cpp ./common/queue.c
mv ./common/bnethashconv.cpp ./common/bnethashconv.c
mv ./common/util.cpp ./common/util.c
mv ./common/fdwatch_epoll.cpp ./common/fdwatch_epoll.c
mv ./common/xalloc.cpp ./common/xalloc.c
mv ./common/bn_type.cpp ./common/bn_type.c
mv ./common/hashtable.cpp ./common/hashtable.c
mv ./common/rlimit.cpp ./common/rlimit.c
mv ./common/fdwatch_kqueue.cpp ./common/fdwatch_kqueue.c
mv ./common/packet.cpp ./common/packet.c
mv ./common/network.cpp ./common/network.c
mv ./common/rcm.cpp ./common/rcm.c
mv ./common/hexdump.cpp ./common/hexdump.c
mv ./common/conf.cpp ./common/conf.c
mv ./common/token.cpp ./common/token.c
mv ./common/d2char_checksum.cpp ./common/d2char_checksum.c
mv ./common/proginfo.cpp ./common/proginfo.c
mv ./common/bnethash.cpp ./common/bnethash.c
mv ./common/eventlog.cpp ./common/eventlog.c
mv ./common/addr.cpp ./common/addr.c
mv ./common/trans.cpp ./common/trans.c
mv ./common/fdwatch_select.cpp ./common/fdwatch_select.c
mv ./common/bnettime.cpp ./common/bnettime.c
mv ./bntrackd/bntrackd.cpp ./bntrackd/bntrackd.c
mv ./bnpass/bnpass.cpp ./bnpass/bnpass.c
mv ./bnpcap/bnpcap.cpp ./bnpcap/bnpcap.c
mv ./compat/difftime.cpp ./compat/difftime.c
mv ./compat/strerror.cpp ./compat/strerror.c
mv ./compat/memcpy.cpp ./compat/memcpy.c
mv ./compat/strftime.cpp ./compat/strftime.c
mv ./compat/strdup.cpp ./compat/strdup.c
mv ./compat/inet_aton.cpp ./compat/inet_aton.c
mv ./compat/memset.cpp ./compat/memset.c
mv ./compat/gettimeofday.cpp ./compat/gettimeofday.c
mv ./compat/psock.cpp ./compat/psock.c
mv ./compat/strsep.cpp ./compat/strsep.c
mv ./compat/strtoul.cpp ./compat/strtoul.c
mv ./compat/pdir.cpp ./compat/pdir.c
mv ./compat/strcasecmp.cpp ./compat/strcasecmp.c
mv ./compat/getopt.cpp ./compat/getopt.c
mv ./compat/uname.cpp ./compat/uname.c
mv ./compat/memmove.cpp ./compat/memmove.c
mv ./compat/vsnprintf.cpp ./compat/vsnprintf.c
mv ./compat/snprintf.cpp ./compat/snprintf.c
mv ./compat/strncasecmp.cpp ./compat/strncasecmp.c
mv ./compat/inet_ntoa.cpp ./compat/inet_ntoa.c
mv ./compat/mmap.cpp ./compat/mmap.c
mv ./d2cs/serverqueue.cpp ./d2cs/serverqueue.c
mv ./d2cs/server.cpp ./d2cs/server.c
mv ./d2cs/xstring.cpp ./d2cs/xstring.c
mv ./d2cs/connection.cpp ./d2cs/connection.c
mv ./d2cs/handle_d2gs.cpp ./d2cs/handle_d2gs.c
mv ./d2cs/handle_bnetd.cpp ./d2cs/handle_bnetd.c
mv ./d2cs/handle_signal.cpp ./d2cs/handle_signal.c
mv ./d2cs/s2s.cpp ./d2cs/s2s.c
mv ./d2cs/game.cpp ./d2cs/game.c
mv ./d2cs/cmdline_parse.cpp ./d2cs/cmdline_parse.c
mv ./d2cs/d2charlist.cpp ./d2cs/d2charlist.c
mv ./d2cs/d2ladder.cpp ./d2cs/d2ladder.c
mv ./d2cs/prefs.cpp ./d2cs/prefs.c
mv ./d2cs/main.cpp ./d2cs/main.c
mv ./d2cs/net.cpp ./d2cs/net.c
mv ./d2cs/d2charfile.cpp ./d2cs/d2charfile.c
mv ./d2cs/conf.cpp ./d2cs/conf.c
mv ./d2cs/handle_d2cs.cpp ./d2cs/handle_d2cs.c
mv ./d2cs/d2gs.cpp ./d2cs/d2gs.c
mv ./d2cs/gamequeue.cpp ./d2cs/gamequeue.c
mv ./d2cs/handle_init.cpp ./d2cs/handle_init.c
mv ./d2cs/bnetd.cpp ./d2cs/bnetd.c
