mv ./autoconf/ansi2knr.c ./autoconf/ansi2knr.cpp
mv ./win32/d2dbs_winmain.c ./win32/d2dbs_winmain.cpp
mv ./win32/winmain.c ./win32/winmain.cpp
mv ./win32/service.c ./win32/service.cpp
mv ./win32/d2cs_winmain.c ./win32/d2cs_winmain.cpp
mv ./bnproxy/bnproxy.c ./bnproxy/bnproxy.cpp
mv ./bnproxy/virtconn.c ./bnproxy/virtconn.cpp
mv ./tinycdb/cdb_find.c ./tinycdb/cdb_find.cpp
mv ./tinycdb/cdb_make.c ./tinycdb/cdb_make.cpp
mv ./tinycdb/cdb_seek.c ./tinycdb/cdb_seek.cpp
mv ./tinycdb/cdb.c ./tinycdb/cdb.cpp
mv ./tinycdb/cdb_make_add.c ./tinycdb/cdb_make_add.cpp
mv ./tinycdb/cdb_make_put.c ./tinycdb/cdb_make_put.cpp
mv ./tinycdb/cdb_seq.c ./tinycdb/cdb_seq.cpp
mv ./tinycdb/cdb_make_find.c ./tinycdb/cdb_make_find.cpp
mv ./tinycdb/cdb_hash.c ./tinycdb/cdb_hash.cpp
mv ./tinycdb/cdb_init.c ./tinycdb/cdb_init.cpp
mv ./tinycdb/cdb_unpack.c ./tinycdb/cdb_unpack.cpp
mv ./tinycdb/cdb_findnext.c ./tinycdb/cdb_findnext.cpp
mv ./client/bnftp.c ./client/bnftp.cpp
mv ./client/client.c ./client/client.cpp
mv ./client/bnbot.c ./client/bnbot.cpp
mv ./client/bnstat.c ./client/bnstat.cpp
mv ./client/udptest.c ./client/udptest.cpp
mv ./client/bnchat.c ./client/bnchat.cpp
mv ./client/client_connect.c ./client/client_connect.cpp
mv ./bnetd/handle_udp.c ./bnetd/handle_udp.cpp
mv ./bnetd/alias_command.c ./bnetd/alias_command.cpp
mv ./bnetd/helpfile.c ./bnetd/helpfile.cpp
mv ./bnetd/server.c ./bnetd/server.cpp
mv ./bnetd/storage_sql.c ./bnetd/storage_sql.cpp
mv ./bnetd/game_conv.c ./bnetd/game_conv.cpp
mv ./bnetd/connection.c ./bnetd/connection.cpp
mv ./bnetd/file_plain.c ./bnetd/file_plain.cpp
mv ./bnetd/account.c ./bnetd/account.cpp
mv ./bnetd/ipban.c ./bnetd/ipban.cpp
mv ./bnetd/adbanner.c ./bnetd/adbanner.cpp
mv ./bnetd/ladder.c ./bnetd/ladder.cpp
mv ./bnetd/tick.c ./bnetd/tick.cpp
mv ./bnetd/attrlayer.c ./bnetd/attrlayer.cpp
mv ./bnetd/message.c ./bnetd/message.cpp
mv ./bnetd/storage_file.c ./bnetd/storage_file.cpp
mv ./bnetd/ladder_binary.c ./bnetd/ladder_binary.cpp
mv ./bnetd/anongame_gameresult.c ./bnetd/anongame_gameresult.cpp
mv ./bnetd/character.c ./bnetd/character.cpp
mv ./bnetd/cmdline.c ./bnetd/cmdline.cpp
mv ./bnetd/game.c ./bnetd/game.cpp
mv ./bnetd/support.c ./bnetd/support.cpp
mv ./bnetd/command_groups.c ./bnetd/command_groups.cpp
mv ./bnetd/topic.c ./bnetd/topic.cpp
mv ./bnetd/sql_dbcreator.c ./bnetd/sql_dbcreator.cpp
mv ./bnetd/attrgroup.c ./bnetd/attrgroup.cpp
mv ./bnetd/sql_mysql.c ./bnetd/sql_mysql.cpp
mv ./bnetd/handle_file.c ./bnetd/handle_file.cpp
mv ./bnetd/handle_anongame.c ./bnetd/handle_anongame.cpp
mv ./bnetd/timer.c ./bnetd/timer.cpp
mv ./bnetd/channel.c ./bnetd/channel.cpp
mv ./bnetd/anongame.c ./bnetd/anongame.cpp
mv ./bnetd/tournament.c ./bnetd/tournament.cpp
mv ./bnetd/mail.c ./bnetd/mail.cpp
mv ./bnetd/udptest_send.c ./bnetd/udptest_send.cpp
mv ./bnetd/prefs.c ./bnetd/prefs.cpp
mv ./bnetd/main.c ./bnetd/main.cpp
mv ./bnetd/output.c ./bnetd/output.cpp
mv ./bnetd/channel_conv.c ./bnetd/channel_conv.cpp
mv ./bnetd/sql_pgsql.c ./bnetd/sql_pgsql.cpp
mv ./bnetd/friends.c ./bnetd/friends.cpp
mv ./bnetd/ladder_calc.c ./bnetd/ladder_calc.cpp
mv ./bnetd/handle_bot.c ./bnetd/handle_bot.cpp
mv ./bnetd/handle_bnet.c ./bnetd/handle_bnet.cpp
mv ./bnetd/versioncheck.c ./bnetd/versioncheck.cpp
mv ./bnetd/clan.c ./bnetd/clan.cpp
mv ./bnetd/sql_odbc.c ./bnetd/sql_odbc.cpp
mv ./bnetd/command.c ./bnetd/command.cpp
mv ./bnetd/handle_irc.c ./bnetd/handle_irc.cpp
mv ./bnetd/handle_d2cs.c ./bnetd/handle_d2cs.cpp
mv ./bnetd/news.c ./bnetd/news.cpp
mv ./bnetd/file_cdb.c ./bnetd/file_cdb.cpp
mv ./bnetd/anongame_infos.c ./bnetd/anongame_infos.cpp
mv ./bnetd/team.c ./bnetd/team.cpp
mv ./bnetd/file.c ./bnetd/file.cpp
mv ./bnetd/anongame_maplists.c ./bnetd/anongame_maplists.cpp
mv ./bnetd/runprog.c ./bnetd/runprog.cpp
mv ./bnetd/tracker.c ./bnetd/tracker.cpp
mv ./bnetd/autoupdate.c ./bnetd/autoupdate.cpp
mv ./bnetd/irc.c ./bnetd/irc.cpp
mv ./bnetd/handle_init.c ./bnetd/handle_init.cpp
mv ./bnetd/sql_sqlite3.c ./bnetd/sql_sqlite3.cpp
mv ./bnetd/storage.c ./bnetd/storage.cpp
mv ./bnetd/handle_telnet.c ./bnetd/handle_telnet.cpp
mv ./bnetd/realm.c ./bnetd/realm.cpp
mv ./bnetd/account_wrap.c ./bnetd/account_wrap.cpp
mv ./bnetd/watch.c ./bnetd/watch.cpp
mv ./d2dbs/dbserver.c ./d2dbs/dbserver.cpp
mv ./d2dbs/dbsdupecheck.c ./d2dbs/dbsdupecheck.cpp
mv ./d2dbs/handle_signal.c ./d2dbs/handle_signal.cpp
mv ./d2dbs/cmdline_parse.c ./d2dbs/cmdline_parse.cpp
mv ./d2dbs/d2ladder.c ./d2dbs/d2ladder.cpp
mv ./d2dbs/dbspacket.c ./d2dbs/dbspacket.cpp
mv ./d2dbs/charlock.c ./d2dbs/charlock.cpp
mv ./d2dbs/prefs.c ./d2dbs/prefs.cpp
mv ./d2dbs/main.c ./d2dbs/main.cpp
mv ./zlib/pvpgn_zutil.c ./zlib/pvpgn_zutil.cpp
mv ./zlib/pvpgn_deflate.c ./zlib/pvpgn_deflate.cpp
mv ./zlib/pvpgn_adler32.c ./zlib/pvpgn_adler32.cpp
mv ./zlib/pvpgn_trees.c ./zlib/pvpgn_trees.cpp
mv ./bniutils/bnilist.c ./bniutils/bnilist.cpp
mv ./bniutils/tgainfo.c ./bniutils/tgainfo.cpp
mv ./bniutils/fileio.c ./bniutils/fileio.cpp
mv ./bniutils/tga.c ./bniutils/tga.cpp
mv ./bniutils/bnibuild.c ./bniutils/bnibuild.cpp
mv ./bniutils/bni.c ./bniutils/bni.cpp
mv ./bniutils/bniextract.c ./bniutils/bniextract.cpp
mv ./bniutils/bni2tga.c ./bniutils/bni2tga.cpp
mv ./common/fdwatch_poll.c ./common/fdwatch_poll.cpp
mv ./common/list.c ./common/list.cpp
mv ./common/fdwatch.c ./common/fdwatch.cpp
mv ./common/give_up_root_privileges.c ./common/give_up_root_privileges.cpp
mv ./common/tag.c ./common/tag.cpp
mv ./common/queue.c ./common/queue.cpp
mv ./common/bnethashconv.c ./common/bnethashconv.cpp
mv ./common/util.c ./common/util.cpp
mv ./common/fdwatch_epoll.c ./common/fdwatch_epoll.cpp
mv ./common/xalloc.c ./common/xalloc.cpp
mv ./common/bn_type.c ./common/bn_type.cpp
mv ./common/hashtable.c ./common/hashtable.cpp
mv ./common/rlimit.c ./common/rlimit.cpp
mv ./common/fdwatch_kqueue.c ./common/fdwatch_kqueue.cpp
mv ./common/packet.c ./common/packet.cpp
mv ./common/network.c ./common/network.cpp
mv ./common/rcm.c ./common/rcm.cpp
mv ./common/hexdump.c ./common/hexdump.cpp
mv ./common/conf.c ./common/conf.cpp
mv ./common/token.c ./common/token.cpp
mv ./common/d2char_checksum.c ./common/d2char_checksum.cpp
mv ./common/proginfo.c ./common/proginfo.cpp
mv ./common/bnethash.c ./common/bnethash.cpp
mv ./common/eventlog.c ./common/eventlog.cpp
mv ./common/addr.c ./common/addr.cpp
mv ./common/trans.c ./common/trans.cpp
mv ./common/fdwatch_select.c ./common/fdwatch_select.cpp
mv ./common/bnettime.c ./common/bnettime.cpp
mv ./bntrackd/bntrackd.c ./bntrackd/bntrackd.cpp
mv ./bnpass/bnpass.c ./bnpass/bnpass.cpp
mv ./bnpcap/bnpcap.c ./bnpcap/bnpcap.cpp
mv ./compat/difftime.c ./compat/difftime.cpp
mv ./compat/strerror.c ./compat/strerror.cpp
mv ./compat/memcpy.c ./compat/memcpy.cpp
mv ./compat/strftime.c ./compat/strftime.cpp
mv ./compat/strdup.c ./compat/strdup.cpp
mv ./compat/inet_aton.c ./compat/inet_aton.cpp
mv ./compat/memset.c ./compat/memset.cpp
mv ./compat/gettimeofday.c ./compat/gettimeofday.cpp
mv ./compat/psock.c ./compat/psock.cpp
mv ./compat/strsep.c ./compat/strsep.cpp
mv ./compat/strtoul.c ./compat/strtoul.cpp
mv ./compat/pdir.c ./compat/pdir.cpp
mv ./compat/strcasecmp.c ./compat/strcasecmp.cpp
mv ./compat/getopt.c ./compat/getopt.cpp
mv ./compat/uname.c ./compat/uname.cpp
mv ./compat/memmove.c ./compat/memmove.cpp
mv ./compat/vsnprintf.c ./compat/vsnprintf.cpp
mv ./compat/snprintf.c ./compat/snprintf.cpp
mv ./compat/strncasecmp.c ./compat/strncasecmp.cpp
mv ./compat/inet_ntoa.c ./compat/inet_ntoa.cpp
mv ./compat/mmap.c ./compat/mmap.cpp
mv ./d2cs/serverqueue.c ./d2cs/serverqueue.cpp
mv ./d2cs/server.c ./d2cs/server.cpp
mv ./d2cs/xstring.c ./d2cs/xstring.cpp
mv ./d2cs/connection.c ./d2cs/connection.cpp
mv ./d2cs/handle_d2gs.c ./d2cs/handle_d2gs.cpp
mv ./d2cs/handle_bnetd.c ./d2cs/handle_bnetd.cpp
mv ./d2cs/handle_signal.c ./d2cs/handle_signal.cpp
mv ./d2cs/s2s.c ./d2cs/s2s.cpp
mv ./d2cs/game.c ./d2cs/game.cpp
mv ./d2cs/cmdline_parse.c ./d2cs/cmdline_parse.cpp
mv ./d2cs/d2charlist.c ./d2cs/d2charlist.cpp
mv ./d2cs/d2ladder.c ./d2cs/d2ladder.cpp
mv ./d2cs/prefs.c ./d2cs/prefs.cpp
mv ./d2cs/main.c ./d2cs/main.cpp
mv ./d2cs/net.c ./d2cs/net.cpp
mv ./d2cs/d2charfile.c ./d2cs/d2charfile.cpp
mv ./d2cs/conf.c ./d2cs/conf.cpp
mv ./d2cs/handle_d2cs.c ./d2cs/handle_d2cs.cpp
mv ./d2cs/d2gs.c ./d2cs/d2gs.cpp
mv ./d2cs/gamequeue.c ./d2cs/gamequeue.cpp
mv ./d2cs/handle_init.c ./d2cs/handle_init.cpp
mv ./d2cs/bnetd.c ./d2cs/bnetd.cpp
